import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

import './globals.css'
const inter = Inter({subsets: ['latin']})

import Navbar from "@/app/components/Navbar";
import AuthProvider from "@/app/components/AuthProvider";

export const metadata: Metadata = {
    title: 'Next Auth',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <Navbar/>
                    <main className="flex justify-center items-start p-6 min-h-screen">
                        {children}
                    </main>
                </AuthProvider>
            </body>
        </html>
    )
}
