import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "@/app/components/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Next Auth',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar/>
                <main className="flex justify-center items-start p-6 min-h-screen">
                    {children}
                </main>
            </body>
        </html>
    )
}
